### ISSUE TITLE
AutoVisor not toggling visor states.

### ISSUE THREAD

**Issue by Avalon304** [Ottermandias/AutoVisor#12]
After the recent update to 6.1 and AutoVisor 1.2.2.0 the plugin doesnt appear to be affecting the visor state if triggers are set up (such as riding a mount, entering an instance, drawing your weapon). Disabling and reinstalling the plugin forces a state change (based on the settings chosen), but after that the plugin no longer changes the visors state. Headslot state, pose selection and weapon state all appear to function properly.

**Comment by Ottermandias** [comment]
Stupid typo. Thanks! :)

**Comment by Avalon304** [comment]
Checked new update. All works well. :D
