### ISSUE TITLE
Update for 6.2

### ISSUE THREAD

**Issue by ichi-obi** [Ottermandias/AutoVisor#16]

**Comment by Luna-Nocturna** [comment]
Hello Ottermandias,

While ichi-obi already made the thread I wanted to add some context to it. I'm speaking for several people in the RP community and we really miss this plugin. While it's called AutoVisor many use this for our cposes instead. It's just nice to differentiate poses between classes/jobs. (A more timid pose for healers, a more daring one for tanks, I'm sure you as developer understands.) Myself personally also used this a lot for the different cposes with weapons drawn.

In short: Myself and others really love your plugin and would like it back! <3

Now we don't want to rush you. Understanding you also have a life of your own. Possibly work on your island sanctuary or the new raids or anything else. But would like to request if you have any plans on updating the plugin in the future. If yes, please take all the time you need. If I can help personally in some way I'd love to. If no that will be a sad day but you shouldn't feel guilty about this. At least we would be having a confirmation on this and will have to seek another solution.

Thanks in advance for any response!

**Comment by Ottermandias** [comment]
Honestly, I just forgot about it. I don't use AutoVisor myself.
I updated the offsets and did a rudimentary check that everything worked (which it seemed to do). Let me know if anything else broke.

**Comment by Luna-Nocturna** [comment]
Wow, many thanks for such a fast response and an update even. I just updated it ingame and so far it seems to work just like before.

From myself and a bunch of others: Thank you very much!

**Comment by TheGokki** [comment]
Yes, thank you! I use AutoVisor daily on all jobs!
