### ISSUE TITLE
6.21 update reminder

### ISSUE THREAD

**Issue by bunnypig** [Ottermandias/AutoVisor#17]
Hello, saw in a previous issue that you had just forgotten to update the plugin and this is just a friendly reminder people still love the plugin.
In no way issued as "please hurry", like I said, just a friendly reminder in case you forgot it again.
You're doing amazing work! Love Gatherbuddy as well.

**Comment by Ottermandias** [comment]
Huh? Did something break with 6.21?

**Comment by bunnypig** [comment]
Alright, just ignore this entire thing. It was an issue with Dalamud it seems. It didn't want to read in any changes to my plugins for some reason. Reinstalled the entire thing and now it just started working. Sorry for wasting your time. Have a great day.

**Comment by sr7olsniper** [comment]
> Alright, just ignore this entire thing. It was an issue with Dalamud it seems. It didn't want to read in any changes to my plugins for some reason. Reinstalled the entire thing and now it just started working. Sorry for wasting your time. Have a great day.

How did you make it work? It has been showing as outdated for me for quite some time now.
