### ISSUE TITLE
Most features don't work for me. The only things that work are Weapon State and Poses.

### ISSUE THREAD

**Issue by voidisme** [Ottermandias/AutoVisor#2]
Visor state, headslot state don't do anything. The default option for weapon state and Poses also don't work. Would be happy to record video if needed.

**Comment by Ottermandias** [comment]
Can you give me more information? What client language are you on, what settings did you set up?

**Comment by voidisme** [comment]
My client language is English. I set up the plugin for my character, and added a few jobs. 
Regarding the issues I can toggle the weapon state, but the same thing won't work for headslot state and visor. Also the default option above the jobs doesn't do anything for me.

Maybe I set it up wrong, but here is an example: https://gfycat.com/lavishpertinentgrub

**Comment by Ottermandias** [comment]
Default handles jobs not set. If you set up DRK and are DRK, default is irrelevant (even for fields you did not enable).
I don't see why your head state toggle would not work, but after changing a setting you might have to wait a few seconds. If it still doesn't work, you could use the testing build (either compile it manually or add the https://raw.githubusercontent.com/Ottermandias/AutoVisor/master/repo.json to your custom repos and install [T].)
and if it still doesn't work enter /xldev, set the log level to debug in the top left window and send me your dalamud log.

**Comment by voidisme** [comment]
The default worked after deleting saved character from the plugin and reinstalling it. 
The testing build also didn't work.

Log file showed error with obtaining the eqpfile.

[log_autovisor.txt](https://github.com/Ottermandias/AutoVisor/files/6881662/log_autovisor.txt)

**Comment by Ottermandias** [comment]
Ah, you fucked up your game installation with TexTools.
Pushed a new update to [T], try again.

**Comment by voidisme** [comment]
It worked! I defragmented and cleaned up the tex tools mods, and the [T] worked. Thank you so much!

**Comment by Ottermandias** [comment]
Great! Gonna push the [T] release to Dalamud Repo soon then.
