### ISSUE TITLE
Update for latest ver?

### ISSUE THREAD

**Issue by guppyfaced** [Ottermandias/AutoVisor#23]
Plz?

**Comment by bunnypig** [comment]
Adding a little more... Appreciative request for an update.
I've been using this plugin for a while and I do really appreciate it. Do you have any plans on updating it? 
I can see a lot of changes being updated and it's been worked on the passed week but I do hope you're planning on updating this plugin, it's awesome and there is no alternative that I have found.

Thank you for all your hard work regarding all of your plugins!

**Comment by Ottermandias** [comment]
it... is updated?

**Comment by corsair980** [comment]
Update works for DT release, however this update (1.3.0.1) doesn't seem to include Viper or Pictomancer as options in the Add Job drop down menu.

**Comment by ryanking44** [comment]
would be cool to add hide weapon options based on location (ex. hide weapon while in cities)
